Bump Selenium Grid Version
iFixit/selenium_setup pull request #17
Opened 2024-01-18 20:46 UTC by ardelato

## Description

This change upgrades the Selenium Grid from approximately version 3.14 to around 4.16.

To implement this upgrade, a TOML configuration file is required. This file is essential for specifying the browsers available on the grid and their corresponding drivers. This setup us to ensure that when there's a request for a new session, the `Distributor` component can accurately match the request with browsers that match the "`browserName`" and "`browserVersion`". The upgrade modified the way Selenium pairs browsers, moving away from matching solely based on "`browserName`". Now, the pairing process also considers "`browserVersion`" and "`platformName`".

Reference: https://ifixit.slack.com/archives/C01DBJK0H7U/p1705535705285359

### CR

There will be a follow-up in the `iFixit/ifixit` repo to drop the requirement of a browser version when sending in a session request. Our PHP tests do not cover different browser versions, so this request option is no longer needed. 

### QA

- [ ] Confirm you can run tests with the new local Selenium Grid.

1. Follow the instructions in https://overlord.ifixit.com/Guide/How+to+setup+Selenium+locally/786
2. When attempting to run the test on Cominor, add the following ENV variable `browser=<chrome driver version>`
	- Example: `platformName=MAC browser=v120.0 test-suite -sm GuideSmokeTest`
	- The driver version can be found in the `selenium-config.toml` file that was generated during the setup process.

Closes: https://github.com/iFixit/ifixit/issues/51629

2024-01-18 20:54 UTC, mlahargou requested changes
dev_block 📱

2024-01-18 20:54 UTC, mlahargou commented on selenium-config.template.toml
> +max-sessions = 2
Let's increase this. I sometimes use many browsers to try to deflake tests. It's just the max, so maybe 20?

2024-01-18 20:54 UTC, mlahargou commented on selenium-config.template.toml
> +stereotype = '{"browserName": "chrome", "browserVersion": "v120.0"}' # Browser version is not used by the Grid, but it is used by the tests to determine which browser to use.
Hmm, if the user's local chrome version is different than this, will things break?

2024-01-18 20:56 UTC, mlahargou commented on selenium-config.template.toml
> +stereotype = '{"browserName": "chrome", "browserVersion": "v120.0"}' # Browser version is not used by the Grid, but it is used by the tests to determine which browser to use.
Oh, I think this should be
```suggestion
stereotype = '{"browserName": "chrome", "browserVersion": "v$full_chrome_version"}' # Browser version is not used by the Grid, but it is used by the tests to determine which browser to use.
```

or something like that

2024-01-18 21:22 UTC, ardelato commented on selenium-config.template.toml
> +stereotype = '{"browserName": "chrome", "browserVersion": "v120.0"}' # Browser version is not used by the Grid, but it is used by the tests to determine which browser to use.
Addressed in [bc4c42f](https://github.com/iFixit/selenium_setup/pull/17/commits/bc4c42f5a25ad7b86315f20b71ff634a8fd19896)

2024-01-18 21:22 UTC, ardelato commented on selenium-config.template.toml
> +max-sessions = 2
Address in [`4fbe4a6` (#17)](https://github.com/iFixit/selenium_setup/pull/17/commits/4fbe4a645bf34329a3c99f730202cd9ed8a426e4)

2024-01-18 21:23 UTC, ardelato commented
un_dev_block ✍️

2024-01-18 21:42 UTC, mlahargou approved these changes
CR 📱 Looks good to me. QA will be the real test.

2024-01-18 23:51 UTC, deltuh-vee commented
dev_block ✊ 
I'm getting this error when running Selenium tests.
![image](https://github.com/iFixit/selenium_setup/assets/5289715/5836cefb-ebeb-4257-b9ef-e84ffa804586)

2024-01-19 05:10 UTC, mlahargou commented
Try adding `version=120.0` (or whatever chrome version you run locally) to the `test-suite` command.

2024-01-19 23:02 UTC, ardelato commented
Paired up with @deltuh-vee and there seems to be something else going on. That said, by dropping the browser version parameter from the request and in the Selenium Grid stereotype the tests were able to run.

However, since that solution required a bit of modification in both the `iFixit/ifixit` repo and this pull, I am going to open the follow-up now and have these two pulls be a pair.

2024-01-22 19:58 UTC, ardelato commented
un_dev_block ⚡ I opened the corresponding pull in `iFixit/ifixit` which should help to avoid the whole `browserVersion` configuration step.

2024-01-22 20:00 UTC, mlahargou approved these changes
CR 📱 Cool!

2024-01-22 22:41 UTC, kthaler commented
dev_block 🦖  - I’m having trouble successfully running the tests. I’ve followed the steps, and can successfully launch selenium:

```
> selenium_setup % ./selenium                                      
> 
> Forwarding port: remote:4428 to localhost:4444
> 
> Launching Selenium...
> 14:30:25.998 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
> 14:30:26.087 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
> 2024-01-22 14:30:26.148:INFO::main: Logging initialized @386ms to org.seleniumhq.jetty9.util.log.StdErrLog
> 14:30:26.437 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
> 14:30:26.567 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444

```

And then I run `echo 4428 > ~/.selenium_port`  in cominor on [this branch](https://github.com/iFixit/ifixit/pull/51703). But when I run the test-suite, I get a bunch of fails displaying: `Failed to connect to 127.0.0.1 port 4428 after 0 ms: Couldn't connect to server`

<details>
<summary>Here is the full error</summary>
<br>
WDGuideSmokeTest error: 

        PHPUnit 10.5.2 by Sebastian Bergmann and contributors.

        Runtime:       PHP 8.2.8
        Configuration: /mnt/ebs/home/kthaler/Code/Tests/phpunit.xml

        EEEEE                                                               5 / 5 (100%)

        Time: 00:00.499, Memory: 20.00 MB

        There were 5 errors:

        1) WDGuideSmokeTest::testCreate
        Facebook\WebDriver\Exception\Internal\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome","platformName":"mac","acceptInsecureCerts":true,"goog:chromeOptions":{"args":["--disk-cache-dir=/tmp/","--hide-scrollbars"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"MAC","acceptSslCerts":true,"goog:chromeOptions":{"args":["--disk-cache-dir=/tmp/","--hide-scrollbars"]}}}

        Recv failure: Connection reset by peer

        /mnt/ebs/home/kthaler/Code/vendor/php-webdriver/webdriver/lib/Exception/Internal/WebDriverCurlException.php:20
        /mnt/ebs/home/kthaler/Code/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:328
        /mnt/ebs/home/kthaler/Code/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:129
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UIDriver.php:41
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UIDriverFactory.php:7
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UIDriverFactory.php:34
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UITestCase.php:10

        2) WDGuideSmokeTest::testGuideCompletion
        Facebook\WebDriver\Exception\Internal\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome","platformName":"mac","acceptInsecureCerts":true,"goog:chromeOptions":{"args":["--disk-cache-dir=/tmp/","--hide-scrollbars"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"MAC","acceptSslCerts":true,"goog:chromeOptions":{"args":["--disk-cache-dir=/tmp/","--hide-scrollbars"]}}}

        Failed to connect to 127.0.0.1 port 4428 after 0 ms: Couldn't connect to server

        /mnt/ebs/home/kthaler/Code/vendor/php-webdriver/webdriver/lib/Exception/Internal/WebDriverCurlException.php:20
        /mnt/ebs/home/kthaler/Code/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:328
        /mnt/ebs/home/kthaler/Code/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:129
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UIDriver.php:41
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UIDriverFactory.php:7
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UIDriverFactory.php:34
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UITestCase.php:10

        3) WDGuideSmokeTest::testGuideEdits
        Facebook\WebDriver\Exception\Internal\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome","platformName":"mac","acceptInsecureCerts":true,"goog:chromeOptions":{"args":["--disk-cache-dir=/tmp/","--hide-scrollbars"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"MAC","acceptSslCerts":true,"goog:chromeOptions":{"args":["--disk-cache-dir=/tmp/","--hide-scrollbars"]}}}

        Failed to connect to 127.0.0.1 port 4428 after 0 ms: Couldn't connect to server

        /mnt/ebs/home/kthaler/Code/vendor/php-webdriver/webdriver/lib/Exception/Internal/WebDriverCurlException.php:20
        /mnt/ebs/home/kthaler/Code/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:328
        /mnt/ebs/home/kthaler/Code/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:129
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UIDriver.php:41
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UIDriverFactory.php:7
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UIDriverFactory.php:34
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UITestCase.php:10

        4) WDGuideSmokeTest::testCreatePlaintext
        Facebook\WebDriver\Exception\Internal\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome","platformName":"mac","acceptInsecureCerts":true,"goog:chromeOptions":{"args":["--disk-cache-dir=/tmp/","--hide-scrollbars"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"MAC","acceptSslCerts":true,"goog:chromeOptions":{"args":["--disk-cache-dir=/tmp/","--hide-scrollbars"]}}}

        Failed to connect to 127.0.0.1 port 4428 after 0 ms: Couldn't connect to server

        /mnt/ebs/home/kthaler/Code/vendor/php-webdriver/webdriver/lib/Exception/Internal/WebDriverCurlException.php:20
        /mnt/ebs/home/kthaler/Code/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:328
        /mnt/ebs/home/kthaler/Code/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:129
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UIDriver.php:41
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UIDriverFactory.php:7
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UIDriverFactory.php:34
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UITestCase.php:10

        5) WDGuideSmokeTest::testEditPlaintext
        Facebook\WebDriver\Exception\Internal\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome","platformName":"mac","acceptInsecureCerts":true,"goog:chromeOptions":{"args":["--disk-cache-dir=/tmp/","--hide-scrollbars"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"MAC","acceptSslCerts":true,"goog:chromeOptions":{"args":["--disk-cache-dir=/tmp/","--hide-scrollbars"]}}}

        Failed to connect to 127.0.0.1 port 4428 after 0 ms: Couldn't connect to server

        /mnt/ebs/home/kthaler/Code/vendor/php-webdriver/webdriver/lib/Exception/Internal/WebDriverCurlException.php:20
        /mnt/ebs/home/kthaler/Code/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:328
        /mnt/ebs/home/kthaler/Code/vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:129
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UIDriver.php:41
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UIDriverFactory.php:7
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UIDriverFactory.php:34
        /mnt/ebs/home/kthaler/Code/Tests/Objects/UITestCase.php:10

        ERRORS!
        Tests: 5, Assertions: 0, Errors: 5.

        Command exit status was 2 and killing signal was null

-------------------------
Tests that failed 1 times
-------------------------
(00:00.60) - WDGuideSmokeTest

Rerun the tests that failed 1 times with this command:
host=amazon test-suite -s WDGuideSmokeTest
</details>

2024-01-22 23:11 UTC, mlahargou commented
> I’m having trouble successfully running tests.

Looks like you are running the wrong selenium server version:
`Selenium server version: 3.141.59`

2024-01-23 00:47 UTC, kthaler commented
> Are you sure you have this branch checked out?

I did not, but after redoing the steps with this branch, I'm getting the same result. Here's the logs when I'm launching selenium on this branch:

```
> Launching Selenium...
> 16:41:52.009 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
> 16:41:52.032 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
> 16:41:53.190 INFO [NodeOptions.getSessionFactories] - Detected 10 available processors
> 16:41:53.227 INFO [NodeOptions.report] - Adding chrome for {"browserName": "chrome","platformName": "mac"} 10 times
> 16:41:53.276 INFO [Node.<init>] - Binding additional locator mechanisms: relative
> 16:41:53.301 INFO [GridModel.setAvailability] - Switching Node 5f1d5ade-1018-4074-9ccd-f1ccf4fdfa75 (uri: http://192.168.1.11:4444) from DOWN to UP
> 16:41:53.302 INFO [LocalDistributor.add] - Added node 5f1d5ade-1018-4074-9ccd-f1ccf4fdfa75 at http://192.168.1.11:4444. Health check every 120s
> 16:41:53.416 INFO [Standalone.execute] - Started Selenium Standalone 4.16.1 (revision 9b4c83354e): http://192.168.1.11:4444

```

2024-01-23 01:32 UTC, ardelato commented
Paired up with Curtis again, there seems to be other factors which could leave to inconsistent behavior such as if there is a `~/.cache/selenium` folder and possible the Java version that is currently installed.

@mlahargou what are your thoughts on punting the update to the local Selenium version for now and work on maybe getting a containerized version of local selenium?

2024-01-23 18:14 UTC, mlahargou commented
QA 📱 

Same as: https://github.com/iFixit/ifixit/pull/51703#issuecomment-1906643810

2024-01-23 18:15 UTC, merged